### ISSUE TITLE
The log file stops recording after it has been modified by a third-party process

### ISSUE THREAD

**Issue by 4const** [umputun/docker-logger#19]
To reproduce the error, try the following test case:
- start docker-logger
- open log file for any container via vim
- edit log file
- save changes 
and then log file stops recording
and i don't have any error in docker-logger.log

**Comment by umputun** [comment]
I'm not sure if this behavior is a sign of any error. Is there a real use case where you need to modify log file and if so - what exactly you expect from the logger in this situation?

**Comment by 4const** [comment]
Logs should continue to write after the file is released

Editing a log file is just an example of lock.

**Comment by umputun** [comment]
the question is why anyone even needs to open the log file for write and modify it.

**Comment by 4const** [comment]
I just accidentally open log file for edit, and eventually lost a few hours before restarting docker-logger container

**Comment by 4const** [comment]
Additional case... You can delete the log file and after that a new file will not be created.

**Comment by umputun** [comment]
I don't think this issue has anything to do with docker-logger implementation. Most likely it is a part of the (un)expected behavior of [lumberjack](https://github.com/natefinch/lumberjack) used by docker-logger to handle files, rotation and so on. I don't see it as a good enough reason to replace or fork lumberjack. However, if you think such behavior is a bug and should be fixed, pls report to lumberjack repo.

**Comment by mikhail-angelov** [comment]
I have the same issue, time after time logs stops to collect, I agree it most likely [lumberjack](https://github.com/natefinch/lumberjack) issue

since the is no workaround for this issue
I recommend to use other solution wich ack similar as this logger

https://docs.fluentd.org/
it allows to collect logs into file
this is example setup

```
#docker-compose.yaml
version: '3.7'

services:
  fluentd:
    image: fluent/fluentd:v1.15-1
    container_name: fluentd
    hostname: fluentd
    restart: unless-stopped
    volumes:
      - ./fluentConf:/fluentd/etc
      - ./logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - webnet

  nginx:
    image: umputun/nginx-le:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      - webnet
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        tag: app.nginx
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/services.conf:/etc/nginx/services.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - '443:443'
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      - LE_EMAIL=test@gmail.com
      - LE_FQDN=test.xyz
networks:
  webnet:
```
config
```
#fluentConf/fluent.conf
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter app.**>
  @type record_transformer
  <record>
    time ${time}
  </record>
</filter>

<match app.**>
  @type copy
  <store>
    @type file
    path /fluentd/log/%Y%m%d-${tag}
    append true
    compress gzip
    <format>
      @type csv
      force_quotes false
      delimiter \t
      fields time,source,log
    </format>
    <buffer time,tag>
      flush_mode interval
      flush_interval 1d
    </buffer>
  </store>
  <store>
    @type stdout
  </store>
</match>
```

**CONS:**
- a bit more complicated to configure
- third party dependency 

**PROS:**
- looks like more stable
- have more options to extend (e.g. copy logs to S3 or ELK)
